name: Test Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print First Name
        run: echo "Mazen"
      - name: Print Last Name
        run: echo "Abdul"
